version: "3.8"

services:
  backend:
    build:
      context: ./backend
    expose:
      - "8000"
    volumes:
      - ./backend/architecture.json:/app/architecture.json
    networks:
      - app-network
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8099:80"
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
